server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8000
  servlet:
    register-default-servlet: on

spring:
  datasource:
    password: Drac@123
    url: jdbc:mysql://localhost:3306/trackingproject?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: TrackPro
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
jwt:
  secret: mak*(!NSKJ@(*21
  expiresIn: 86400000

